[ios_routers]
csr1000v ansible_host=192.168.56.101

[ios_routers:vars]
ansible_user=cisco
ansible_password=cisco
ansible_network_os=cisco.ios.ios
ansible_connection=ansible.netcommon.network_cli
ansible_become=yes
ansible_become_method=enable
ansible_become_password=cisco
