[ios_routers]
csr1000v ansible_host=192.168.56.101

[ios_routers:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios
ansible_user=cisco
ansible_password=cisco
ansible_ssh_pass=cisco
ansible_become=no
ansible_network_cli_ssh_type=paramiko
ansible_paramiko_look_for_keys=False
ansible_paramiko_host_key_checking=False
ansible_ssh_common_args='-o PubkeyAuthentication=no -o PreferredAuthentications=password'
