version: "3.8"

services:
  automator:
    build: .
    container_name: net_automator
    volumes:
      - ./:/workspace
    environment:
      DEVICE_HOST: ${DEVICE_HOST:-192.168.56.101}
      DEVICE_PORT: ${DEVICE_PORT:-830}
      DEVICE_USER: ${DEVICE_USER:-cisco}
      DEVICE_PASS: ${DEVICE_PASS:-cisco}
    network_mode: "host"
    tty: true
